---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check ufw is installed
      ansible.builtin.command: dpkg -s ufw
      changed_when: false

    - name: Check ufw status
      ansible.builtin.command: ufw status
      register: ufw_status_result
      changed_when: false

    - name: Assert ufw is active
      ansible.builtin.assert:
        that: "'active' in ufw_status_result.stdout.lower()"
