---
- name: Base server setup
  ansible.builtin.import_playbook: base.yml

- name: Nginx server setup
  hosts: nginx_servers
  become: true

  roles:
    - certbot
    # Add your web server role here, e.g.:
    # - nginx
    # - passenger
