---
- name: Update system packages
  hosts: all
  become: true

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"
