---
- name: Install essenttials packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - tmux
    - ntp
    - vim
    - iotop
    - htop
    - atop
    - mc
    - zsh
    - git
    - git-core
    - unzip
    - wget
    - curl
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - software-properties-common
    - libffi-dev
    - dirmngr
    - gnupg
    - apt-transport-https
    - ca-certificates
