---
- name: Install logrotate
  ansible.builtin.apt:
    name: logrotate
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Configure logrotate
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: "0644"
