---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check logrotate is installed
      ansible.builtin.command: dpkg -s logrotate
      changed_when: false

    - name: Check logrotate.conf is managed by Ansible
      ansible.builtin.command: grep -q "managed by Ansible" /etc/logrotate.conf
      changed_when: false
