---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check logrotate is installed
      command: dpkg -s logrotate
      changed_when: false

    - name: Check logrotate.conf exists and is managed by Ansible
      command: grep -q "managed by Ansible" /etc/logrotate.conf
      changed_when: false
