---
- name: Install ufw
  apt:
    name: ufw
    state: latest

- name: Reset ufw
  ufw:
    state: reset

- name: Allow incoming SSH
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow incoming HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow incoming HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Deny incoming traffic
  ufw:
    policy: deny
    direction: incoming

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
