---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check fail2ban package is installed
      ansible.builtin.command: dpkg -s fail2ban
      changed_when: false

    - name: Check jail.local exists
      ansible.builtin.stat:
        path: /etc/fail2ban/jail.local
      register: fail2ban_jail_local

    - name: Assert jail.local is present
      ansible.builtin.assert:
        that: fail2ban_jail_local.stat.exists

    - name: Check fail2ban.local exists
      ansible.builtin.stat:
        path: /etc/fail2ban/fail2ban.local
      register: fail2ban_config_local

    - name: Assert fail2ban.local is present
      ansible.builtin.assert:
        that: fail2ban_config_local.stat.exists
