---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Copy fail2ban.local
  ansible.builtin.template:
    src: fail2ban.local
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Copy jail.local
  ansible.builtin.template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Start and enable fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
